#:schema https://raw.githubusercontent.com/git-town/git-town/refs/heads/main/docs/git-town.schema.json

# See https://www.git-town.com/configuration-file for details

[branches]
main = "main"
perennials = ["main"] 

[hosting]
dev-remote = "origin"
github-connector = "gh"

[sync]
feature-strategy = "rebase"
push-hook = false
