packages:
  - .
  - worker
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - preact@10.28.2
  - lodash@4.18.1
  # Renovate security update: hono@4.12.18
  - hono@4.12.18
  # Renovate security update: axios@1.15.2
  - axios@1.15.2
  # Renovate security update: hono@<4.12.12@4.12.18
  - hono@<4.12.12@4.12.18
overrides:
  '@hono/node-server@<1.19.13': '>=1.19.14'
  tmp@<=0.2.3: '>=0.2.5'
  hono@<4.12.12: '>=4.12.18'
allowBuilds:
  core-js-pure: false
  esbuild: false
  sharp: false
  unrs-resolver: false
  workerd: false
